spring.application.name=api_scheduling_system
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=scheduling_system;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=serv
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


api.security.token.secret=${JWT_SECRET:12345678}